[[redirects]]
  from = "/api/*"
  to = "https://api.nexon.co.kr/kart/v1.0/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  

[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"
  

  
